name: Demo on workflow events
on: push
jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
            - name: Print the trigger type using {{ github.event_name }}
              run: echo "This is coming from ${{ github.event_name }}"